/**
--------------------------------------------------------------------------------------
 * @Author      :   Mayank Kumar
 * @name        :   Mass_Permission_Set_Assignment
 * @CreateDate  :   23rd June,2019
 * @Description :   Permission sets mass assigments to market users
 * @Version     :   <1.0>
 * @reference   :   
--------------------------------------------------------------------------------------
 **/
public without sharing class Mass_Permission_Set_Assignment{
}